// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-14 15:44:29 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SayPeopleLeftSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SayPeopleLeftSkill stateMachine("SayPeopleLeft");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SayPeopleLeftSkill successfully closed" << std::endl;
  return ret;
}

