// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-16 12:58:24 CET
// This is an automatically generated file.

#include "SayPeopleLeftSkill.h"
#include <future>
#include <QTimer>
#include <QDebug>
#include <QCoreApplication>

#include <QTime>
#include <iostream>
#include <QStateMachine>
#include <cstdlib>
#include <type_traits>

template<typename T>
T convert(const std::string& str) {
    if constexpr (std::is_same_v<T, int>) {
        return std::stoi(str);
    } else if constexpr (std::is_same_v<T, double>) {
        return std::stod(str);
    } else if constexpr (std::is_same_v<T, float>) {
        return std::stof(str);
    } 
    else if constexpr (std::is_same_v<T, bool>) { 
        if (str == "true" || str == "1") { 
            return true; 
        } else if (str == "false" || str == "0") { 
            return false; 
        } else { 
            throw std::invalid_argument("Invalid boolean value"); 
        } 
    } 
    else if constexpr (std::is_same_v<T, std::string>) {
        return str;
    }
    else {
        throw std::invalid_argument("Unsupported type conversion");
    }
}

SayPeopleLeftSkill::SayPeopleLeftSkill(std::string name ) :
		m_name(std::move(name))
{
    
}

SayPeopleLeftSkill::~SayPeopleLeftSkill()
{
    //std::cout << "DEBUG: Invoked destructor of SayPeopleLeftSkill" << std::endl;
    m_threadSpin->join();
}

void SayPeopleLeftSkill::spin(std::shared_ptr<rclcpp::Node> node)
{
    rclcpp::spin(node);
    rclcpp::shutdown();
    QCoreApplication::quit();
    //std::cout << "DEBUG: SayPeopleLeftSkill::spin successfully ended" << std::endl;
}

bool SayPeopleLeftSkill::start(int argc, char*argv[])
{
	if(!rclcpp::ok())
	{
		rclcpp::init(/*argc*/ argc, /*argv*/ argv);
	}

	m_node = rclcpp::Node::make_shared(m_name + "Skill");
	RCLCPP_DEBUG_STREAM(m_node->get_logger(), "SayPeopleLeftSkill::start");
	std::cout << "DEBUG: SayPeopleLeftSkill::start" << std::endl;

  
	m_tickService = m_node->create_service<bt_interfaces_dummy::srv::TickAction>(m_name + "Skill/tick",
                                                                           	std::bind(&SayPeopleLeftSkill::tick,
                                                                           	this,
                                                                           	std::placeholders::_1,
                                                                           	std::placeholders::_2));
  m_tickService->configure_introspection(m_node->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
	m_haltService = m_node->create_service<bt_interfaces_dummy::srv::HaltAction>(m_name + "Skill/halt",
                                                                            	std::bind(&SayPeopleLeftSkill::halt,
                                                                            	this,
                                                                            	std::placeholders::_1,
                                                                            	std::placeholders::_2));
  m_haltService->configure_introspection(m_node->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  
  
  nodeSpeak = rclcpp::Node::make_shared(m_name + "SkillNodeSpeak");
  clientSpeak = nodeSpeak->create_client<text_to_speech_interfaces::srv::Speak>("/TextToSpeechComponent/Speak");
  clientSpeak->configure_introspection(nodeSpeak->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientSpeak->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'Speak'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'Speak'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'TextToSpeechComponent/Speak' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("TextToSpeechComponent.Speak.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<text_to_speech_interfaces::srv::Speak::Request>();
      auto eventParams = event.data().toMap();
      
      request->text = convert<decltype(request->text)>(eventParams["text"].toString().toStdString());
      auto result = clientSpeak->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeSpeak, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           m_stateMachine.submitEvent("TextToSpeechComponent.Speak.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TextToSpeechComponent.Speak.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'Speak'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'Speak'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("TextToSpeechComponent.Speak.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TextToSpeechComponent.Speak.Return");
  });
  nodeIsSpeaking = rclcpp::Node::make_shared(m_name + "SkillNodeIsSpeaking");
  clientIsSpeaking = nodeIsSpeaking->create_client<text_to_speech_interfaces::srv::IsSpeaking>("/TextToSpeechComponent/IsSpeaking");
  clientIsSpeaking->configure_introspection(nodeIsSpeaking->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientIsSpeaking->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'IsSpeaking'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'IsSpeaking'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'TextToSpeechComponent/IsSpeaking' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("TextToSpeechComponent.IsSpeaking.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<text_to_speech_interfaces::srv::IsSpeaking::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientIsSpeaking->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeIsSpeaking, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("is_speaking", response->is_speaking);
           m_stateMachine.submitEvent("TextToSpeechComponent.IsSpeaking.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TextToSpeechComponent.IsSpeaking.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'IsSpeaking'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'IsSpeaking'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("TextToSpeechComponent.IsSpeaking.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TextToSpeechComponent.IsSpeaking.Return");
  });
  nodeSetCommand = rclcpp::Node::make_shared(m_name + "SkillNodeSetCommand");
  clientSetCommand = nodeSetCommand->create_client<scheduler_interfaces::srv::SetCommand>("/SchedulerComponent/SetCommand");
  clientSetCommand->configure_introspection(nodeSetCommand->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientSetCommand->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'SetCommand'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'SetCommand'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'SchedulerComponent/SetCommand' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("SchedulerComponent.SetCommand.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<scheduler_interfaces::srv::SetCommand::Request>();
      auto eventParams = event.data().toMap();
      
      request->command = convert<decltype(request->command)>(eventParams["command"].toString().toStdString());
      auto result = clientSetCommand->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeSetCommand, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("is_ok", response->is_ok);
           m_stateMachine.submitEvent("SchedulerComponent.SetCommand.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "SchedulerComponent.SetCommand.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'SetCommand'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'SetCommand'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("SchedulerComponent.SetCommand.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "SchedulerComponent.SetCommand.Return");
  });
  nodeGetCurrentAction = rclcpp::Node::make_shared(m_name + "SkillNodeGetCurrentAction");
  clientGetCurrentAction = nodeGetCurrentAction->create_client<scheduler_interfaces::srv::GetCurrentAction>("/SchedulerComponent/GetCurrentAction");
  clientGetCurrentAction->configure_introspection(nodeGetCurrentAction->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientGetCurrentAction->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'GetCurrentAction'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'GetCurrentAction'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'SchedulerComponent/GetCurrentAction' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("SchedulerComponent.GetCurrentAction.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<scheduler_interfaces::srv::GetCurrentAction::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientGetCurrentAction->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeGetCurrentAction, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("param", response->param.c_str());
           m_stateMachine.submitEvent("SchedulerComponent.GetCurrentAction.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "SchedulerComponent.GetCurrentAction.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'GetCurrentAction'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'GetCurrentAction'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("SchedulerComponent.GetCurrentAction.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "SchedulerComponent.GetCurrentAction.Return");
  });
  
  m_stateMachine.connectToEvent("TICK_RESPONSE", [this]([[maybe_unused]]const QScxmlEvent & event){
    RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::tickReturn %s", event.data().toMap()["status"].toString().toStdString().c_str());
    std::string result = event.data().toMap()["status"].toString().toStdString();
    if (result == std::to_string(SKILL_SUCCESS) )
    {
      m_tickResult.store(Status::success);
    }
    else if (result == std::to_string(SKILL_RUNNING) )
    {
      m_tickResult.store(Status::running);
    }
    else if (result == std::to_string(SKILL_FAILURE) )
    { 
      m_tickResult.store(Status::failure);
    }
  });
    
  m_stateMachine.connectToEvent("HALT_RESPONSE", [this]([[maybe_unused]]const QScxmlEvent & event){
    RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::haltresponse");
    m_haltResult.store(true);
  });

  
  
  
  

	m_stateMachine.start();
	m_threadSpin = std::make_shared<std::thread>(spin, m_node);
       
	return true;
}

void SayPeopleLeftSkill::tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Request> request,
                                std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Response>      response)
{
  std::lock_guard<std::mutex> lock(m_requestMutex);
  RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::tick");
  m_tickResult.store(Status::undefined);
  m_stateMachine.submitEvent("CMD_TICK");
  
  int load_counter=0;
  auto start_timer = std::chrono::steady_clock::now();
  while(m_tickResult.load()== Status::undefined) {
      std::this_thread::sleep_for (std::chrono::milliseconds(5));
      load_counter++;
  }
  auto end_timer = std::chrono::steady_clock::now();
  auto duration_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_timer - start_timer).count();
  switch(m_tickResult.load()) 
  {
      case Status::running:
          response->status = SKILL_RUNNING;
          break;
      case Status::failure:
          response->status = SKILL_FAILURE;
          break;
      case Status::success:
          response->status = SKILL_SUCCESS;
          break;
      case Status::undefined:
          response->status = SKILL_FAILURE;
          break;
  }
  RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::tickDone");
  RCLCPP_DEBUG(m_node->get_logger(), "SayPeopleLeftSkill num_retry: %d tick time: %ld", load_counter, duration_ms);
  response->is_ok = true;
}

void SayPeopleLeftSkill::halt( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Request> request,
    [[maybe_unused]] std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Response> response)
{
  std::lock_guard<std::mutex> lock(m_requestMutex);
  RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::halt");
  m_haltResult.store(false);
  m_stateMachine.submitEvent("CMD_HALT");
  while(!m_haltResult.load()) {
      std::this_thread::sleep_for (std::chrono::milliseconds(100));
  }
  RCLCPP_INFO(m_node->get_logger(), "SayPeopleLeftSkill::haltDone");
  response->is_ok = true;
}








