// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-12 14:59:45 UTC
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "GoToPoiActionSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  GoToPoiActionSkill stateMachine("GoToPoiAction");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "GoToPoiActionSkill successfully closed" << std::endl;
  return ret;
}

