// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-27 12:46:18 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SetPoi8Skill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SetPoi8Skill stateMachine("SetPoi8");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SetPoi8Skill successfully closed" << std::endl;
  return ret;
}

