// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-11-28 11:02:14 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SetPoi3Skill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SetPoi3Skill stateMachine("SetPoi3");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SetPoi3Skill successfully closed" << std::endl;
  return ret;
}

