// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-11-26 16:09:55 CET
// This is an automatically generated file.

# pragma once

#include <mutex>
#include <thread>
#include <rclcpp/rclcpp.hpp>
#include "rclcpp_action/rclcpp_action.hpp"
#include "ArePeoplePresentSkillSM.h"
#include <bt_interfaces_dummy/msg/condition_response.hpp>
#include <turn_back_manager_interfaces/srv/is_allowed_to_continue.hpp> 



#include <bt_interfaces_dummy/srv/tick_condition.hpp>


#include <rcl/service_introspection.h>

#define SERVICE_TIMEOUT 8
#define SKILL_SUCCESS 0
#define SKILL_FAILURE 1
#define SKILL_RUNNING 2

enum class Status{
	undefined,
	success,
	failure
};

class ArePeoplePresentSkill
{
public:
	ArePeoplePresentSkill(std::string name );
    ~ArePeoplePresentSkill();

	bool start(int argc, char * argv[]);
	static void spin(std::shared_ptr<rclcpp::Node> node);
	
	void tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Request> request,
			   std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Response>      response);
	
	
	

private:
	std::shared_ptr<std::thread> m_threadSpin;
	std::shared_ptr<rclcpp::Node> m_node;
	std::mutex m_requestMutex;
	std::string m_name;
	ArePeoplePresentSkillCondition m_stateMachine;
	std::atomic<Status> m_tickResult{Status::undefined};
	rclcpp::Service<bt_interfaces_dummy::srv::TickCondition>::SharedPtr m_tickService;
	
	
	
	
	
	
	std::shared_ptr<rclcpp::Node> nodeIsAllowedToContinue;
	std::shared_ptr<rclcpp::Client<turn_back_manager_interfaces::srv::IsAllowedToContinue>> clientIsAllowedToContinue;
	
	

};

