// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-12-03 09:25:28 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SaySkipQuestionsSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SaySkipQuestionsSkill stateMachine("SaySkipQuestions");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SaySkipQuestionsSkill successfully closed" << std::endl;
  return ret;
}

