// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-14 15:44:28 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "IsWarningDurationSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  IsWarningDurationSkill stateMachine("IsWarningDuration");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "IsWarningDurationSkill successfully closed" << std::endl;
  return ret;
}

