// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-20 14:13:13 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "IsAllowedToMoveSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  IsAllowedToMoveSkill stateMachine("IsAllowedToMove");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "IsAllowedToMoveSkill successfully closed" << std::endl;
  return ret;
}

