// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-12-11 15:29:22 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SetPoi10Skill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SetPoi10Skill stateMachine("SetPoi10");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SetPoi10Skill successfully closed" << std::endl;
  return ret;
}

