// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-14 15:44:28 CET
// This is an automatically generated file.

#include "IsTimerDoneSkill.h"
#include <future>
#include <QTimer>
#include <QDebug>
#include <QCoreApplication>

#include <QTime>
#include <iostream>
#include <QStateMachine>
#include <cstdlib>
#include <type_traits>

template<typename T>
T convert(const std::string& str) {
    if constexpr (std::is_same_v<T, int>) {
        return std::stoi(str);
    } else if constexpr (std::is_same_v<T, double>) {
        return std::stod(str);
    } else if constexpr (std::is_same_v<T, float>) {
        return std::stof(str);
    } 
    else if constexpr (std::is_same_v<T, bool>) { 
        if (str == "true" || str == "1") { 
            return true; 
        } else if (str == "false" || str == "0") { 
            return false; 
        } else { 
            throw std::invalid_argument("Invalid boolean value"); 
        } 
    } 
    else if constexpr (std::is_same_v<T, std::string>) {
        return str;
    }
    else {
        throw std::invalid_argument("Unsupported type conversion");
    }
}

IsTimerDoneSkill::IsTimerDoneSkill(std::string name ) :
		m_name(std::move(name))
{
    
}

IsTimerDoneSkill::~IsTimerDoneSkill()
{
    //std::cout << "DEBUG: Invoked destructor of IsTimerDoneSkill" << std::endl;
    m_threadSpin->join();
}

void IsTimerDoneSkill::spin(std::shared_ptr<rclcpp::Node> node)
{
    rclcpp::spin(node);
    rclcpp::shutdown();
    QCoreApplication::quit();
    //std::cout << "DEBUG: IsTimerDoneSkill::spin successfully ended" << std::endl;
}

bool IsTimerDoneSkill::start(int argc, char*argv[])
{
	if(!rclcpp::ok())
	{
		rclcpp::init(/*argc*/ argc, /*argv*/ argv);
	}

	m_node = rclcpp::Node::make_shared(m_name + "Skill");
	RCLCPP_DEBUG_STREAM(m_node->get_logger(), "IsTimerDoneSkill::start");
	std::cout << "DEBUG: IsTimerDoneSkill::start" << std::endl;

  
	m_tickService = m_node->create_service<bt_interfaces_dummy::srv::TickCondition>(m_name + "Skill/tick",
                                                                           	std::bind(&IsTimerDoneSkill::tick,
                                                                           	this,
                                                                           	std::placeholders::_1,
                                                                           	std::placeholders::_2));
  m_tickService->configure_introspection(m_node->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  
  
  
  nodeIsTimerActive = rclcpp::Node::make_shared(m_name + "SkillNodeIsTimerActive");
  clientIsTimerActive = nodeIsTimerActive->create_client<timer_check_for_people_interfaces::srv::IsTimerActive>("/TimerCheckForPeopleComponent/IsTimerActive");
  clientIsTimerActive->configure_introspection(nodeIsTimerActive->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientIsTimerActive->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'IsTimerActive'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'IsTimerActive'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'TimerCheckForPeopleComponent/IsTimerActive' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("TimerCheckForPeopleComponent.IsTimerActive.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<timer_check_for_people_interfaces::srv::IsTimerActive::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientIsTimerActive->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeIsTimerActive, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           m_stateMachine.submitEvent("TimerCheckForPeopleComponent.IsTimerActive.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TimerCheckForPeopleComponent.IsTimerActive.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'IsTimerActive'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'IsTimerActive'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("TimerCheckForPeopleComponent.IsTimerActive.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "TimerCheckForPeopleComponent.IsTimerActive.Return");
  });
  
  m_stateMachine.connectToEvent("TICK_RESPONSE", [this]([[maybe_unused]]const QScxmlEvent & event){
    RCLCPP_INFO(m_node->get_logger(), "IsTimerDoneSkill::tickReturn %s", event.data().toMap()["status"].toString().toStdString().c_str());
    std::string result = event.data().toMap()["status"].toString().toStdString();
    if (result == std::to_string(SKILL_SUCCESS) )
    {
      m_tickResult.store(Status::success);
    }
    else if (result == std::to_string(SKILL_FAILURE) )
    { 
      m_tickResult.store(Status::failure);
    }
  });
    

  
  
  
  

	m_stateMachine.start();
	m_threadSpin = std::make_shared<std::thread>(spin, m_node);
       
	return true;
}

void IsTimerDoneSkill::tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Request> request,
                                std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Response>      response)
{
  std::lock_guard<std::mutex> lock(m_requestMutex);
  RCLCPP_INFO(m_node->get_logger(), "IsTimerDoneSkill::tick");
  m_tickResult.store(Status::undefined);
  m_stateMachine.submitEvent("CMD_TICK");
  
  int load_counter=0;
  auto start_timer = std::chrono::steady_clock::now();
  while(m_tickResult.load()== Status::undefined) {
      std::this_thread::sleep_for (std::chrono::milliseconds(5));
      load_counter++;
  }
  auto end_timer = std::chrono::steady_clock::now();
  auto duration_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_timer - start_timer).count();
  switch(m_tickResult.load()) 
  {
      
      case Status::failure:
          response->status = SKILL_FAILURE;
          break;
      case Status::success:
          response->status = SKILL_SUCCESS;
          break;
      case Status::undefined:
          response->status = SKILL_FAILURE;
          break;
  }
  RCLCPP_INFO(m_node->get_logger(), "IsTimerDoneSkill::tickDone");
  RCLCPP_DEBUG(m_node->get_logger(), "IsTimerDoneSkill num_retry: %d tick time: %ld", load_counter, duration_ms);
  response->is_ok = true;
}








