// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-02-02 19:25:13 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "ResetTourAndFlagsSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  ResetTourAndFlagsSkill stateMachine("ResetTourAndFlags");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "ResetTourAndFlagsSkill successfully closed" << std::endl;
  return ret;
}

