ARG base_img=ste93/convince:qt_6.7.3_ubuntu22.04_jazzy_stable_sim
FROM $base_img
LABEL maintainer="Stefano Bernagozzi"
USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update 
RUN apt-get install -y libczmq-dev ros-jazzy-zmqpp-vendor-dbgsym ros-jazzy-zmqpp-vendor libczmq-dev libczmq4 curl 

RUN apt install qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev libboost-all-dev -y

RUN usermod -a -G audio user1
# install behavior tree.cpp v3.8
WORKDIR /home/user1
RUN /bin/bash -c "git clone --recurse-submodules https://github.com/BehaviorTree/BehaviorTree.CPP.git -b v3.8 && \
    cd BehaviorTree.CPP && \
    cmake -S . -B build && \
    cmake --build build && \
    cmake --install build"

RUN pip install reelay websocket-client jedi prompt_toolkit

RUN /bin/bash -c "git clone --recurse-submodules https://github.com/BehaviorTree/Groot.git && \
    cd Groot && \
    cmake -S . -B build && \
    cmake --build build && \
    cmake --install build"

USER user1
WORKDIR /home/user1 

RUN /bin/bash -c "cd /home/user1 && rm -rf ROSMonitoring"

RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    cd /home/user1 && git clone https://github.com/ste93/ROSMonitoring.git -b ros2"

RUN /bin/bash -c "cd /home/user1 && \
    sudo apt install maven openjdk-21-jdk -y && \
    git clone https://github.com/apache/commons-scxml.git && \
    cd commons-scxml && \
    mvn && \
    mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=target/commons-scxml2-2.0-SNAPSHOT.jar"


RUN /bin/bash -c "sudo apt install gobject-introspection libgirepository1.0-dev -y && \
cd /home/user1/ && \
python3 -m venv monitoring-python-env && \
/home/user1/monitoring-python-env/bin/pip install --upgrade pip && \
/home/user1/monitoring-python-env/bin/pip install websocket_client rospy_message_converter pyyaml reelay jedi pycairo PyGObject prompt_toolkit"


RUN echo "export PATH=\$PATH:/home/user1/Groot/build" >> ~/.bashrc

RUN /bin/bash -c "echo 'updated on 2025023061457' && \
    source /opt/ros/jazzy/setup.bash && \
    cd /home/user1/ && \
    git clone https://github.com/convince-project/MOON.git -b dev/model-monitoring && \
    cd /home/user1/MOON/ModelMonitor/modeloracle && \
    mvn install"


RUN /bin/bash -c "echo 'updated on 202503250921' && \
    source /opt/ros/jazzy/setup.bash && \
    cd /home/user1 && \
    git clone https://github.com/convince-project/UC3.git && \
    source /opt/ros/jazzy/setup.bash && \
    cd /home/user1/UC3/ && \
    colcon build --base-paths src/* --packages-ignore face_expressions_wrapper dialog_component"


RUN echo "source /home/user1/UC3/install/setup.bash" >> ~/.bashrc


RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file /home/user1/UC3/monitoring/monitor_prop1.yaml && \
    /home/user1/monitoring-python-env/bin/python generator --config_file /home/user1/UC3/monitoring/monitor_prop2.yaml && \
    /home/user1/monitoring-python-env/bin/python generator --config_file /home/user1/UC3/monitoring/monitor_prop3.yaml && \
    cd /home/user1/UC3/monitoring/monitor_prop1_ws/src/ && \
    colcon build && \
    cd /home/user1/UC3/monitoring/monitor_prop2_ws/src/ && \
    colcon build && \
    cd /home/user1/UC3/monitoring/monitor_prop3_ws/src/ && \
    colcon build"


RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    cd /home/user1/MOON/ModelMonitor/config_generator && \
    python3 config_gen.py --monitor-ws-path /home/user1/UC3/monitoring/monitor_BatteryLevelSkill/src --oracle-address 127.0.0.1:8081 /home/user1/UC3/model-high-level/Skills/BatteryLevelSkill.scxml && \
    python3 config_gen.py --monitor-ws-path /home/user1/UC3/monitoring/monitor_AlarmSkill/src --oracle-address 127.0.0.1:8082 /home/user1/UC3/model-high-level/Skills/AlarmSkill.scxml && \
    python3 config_gen.py --monitor-ws-path /home/user1/UC3/monitoring/monitor_IsPoiDone1Skill/src --oracle-address 127.0.0.1:8083 /home/user1/UC3/model-high-level/Skills/IsPoiDone1Skill.scxml && \
    python3 config_gen.py --monitor-ws-path /home/user1/UC3/monitoring/monitor_SetPoi1Skill/src --oracle-address 127.0.0.1:8084 /home/user1/UC3/model-high-level/Skills/SetPoi1Skill.scxml && \
    python3 config_gen.py --monitor-ws-path /home/user1/UC3/monitoring/monitor_SetCurrentPoiDoneSkill/src --oracle-address 127.0.0.1:8084 /home/user1/UC3/model-high-level/Skills/SetCurrentPoiDoneSkill.scxml"

RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file  /home/user1/MOON/ModelMonitor/config_generator/monitor_BatteryLevelSkill.yaml && \
    cd /home/user1/UC3/monitoring/monitor_BatteryLevelSkill/src && \
    colcon build && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file  /home/user1/MOON/ModelMonitor/config_generator/monitor_AlarmSkill.yaml && \
    cd /home/user1/UC3/monitoring/monitor_AlarmSkill/src && \
    colcon build && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file  /home/user1/MOON/ModelMonitor/config_generator/monitor_IsPoiDone1Skill.yaml && \
    cd /home/user1/UC3/monitoring/monitor_IsPoiDone1Skill/src && \
    colcon build && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file  /home/user1/MOON/ModelMonitor/config_generator/monitor_SetPoi1Skill.yaml && \
    cd /home/user1/UC3/monitoring/monitor_SetPoi1Skill/src && \
    colcon build  && \
    cd /home/user1/ROSMonitoring/generator/ros2_devel && \
    /home/user1/monitoring-python-env/bin/python generator --config_file  /home/user1/MOON/ModelMonitor/config_generator/monitor_SetCurrentPoiDoneSkill.yaml && \
    cd /home/user1/UC3/monitoring/monitor_SetCurrentPoiDoneSkill/src && \
    colcon build"

ENV PATH=${PATH}:/home/user1/.local/bin

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/



