// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-02-11 15:39:41 CET with M2C version 1.0.0
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "IsPoiDone7Skill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  IsPoiDone7Skill stateMachine("IsPoiDone7");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "IsPoiDone7Skill successfully closed" << std::endl;
  return ret;
}

