int32 duplicate_index # The index of the question that is semantically a duplicate of the one just received
string context # based on the context, the conversation is managed by different LLMs, or by predefined replies. We take this information as an input to store the history of the conversation for each case
string interaction # interaction within a conversation
---
string[] reply # The text to be spoken
bool is_ok