// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-20 14:13:14 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SetPoi4Skill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SetPoi4Skill stateMachine("SetPoi4");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SetPoi4Skill successfully closed" << std::endl;
  return ret;
}

