string audio_name
float32 audio_time #optional, if the value is different from 0.0, the dance will be adapted to the speech time, otherwise the dance will be performed with its original duration
---
bool is_ok
string error_msg