// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-14 15:44:29 CET
// This is an automatically generated file.

#include "StopAndTurnBackSkill.h"
#include <future>
#include <QTimer>
#include <QDebug>
#include <QCoreApplication>

#include <QTime>
#include <iostream>
#include <QStateMachine>
#include <cstdlib>
#include <type_traits>

template<typename T>
T convert(const std::string& str) {
    if constexpr (std::is_same_v<T, int>) {
        return std::stoi(str);
    } else if constexpr (std::is_same_v<T, double>) {
        return std::stod(str);
    } else if constexpr (std::is_same_v<T, float>) {
        return std::stof(str);
    } 
    else if constexpr (std::is_same_v<T, bool>) { 
        if (str == "true" || str == "1") { 
            return true; 
        } else if (str == "false" || str == "0") { 
            return false; 
        } else { 
            throw std::invalid_argument("Invalid boolean value"); 
        } 
    } 
    else if constexpr (std::is_same_v<T, std::string>) {
        return str;
    }
    else {
        throw std::invalid_argument("Unsupported type conversion");
    }
}

StopAndTurnBackSkill::StopAndTurnBackSkill(std::string name ) :
		m_name(std::move(name))
{
    
}

StopAndTurnBackSkill::~StopAndTurnBackSkill()
{
    //std::cout << "DEBUG: Invoked destructor of StopAndTurnBackSkill" << std::endl;
    m_threadSpin->join();
}

void StopAndTurnBackSkill::spin(std::shared_ptr<rclcpp::Node> node)
{
    rclcpp::spin(node);
    rclcpp::shutdown();
    QCoreApplication::quit();
    //std::cout << "DEBUG: StopAndTurnBackSkill::spin successfully ended" << std::endl;
}

bool StopAndTurnBackSkill::start(int argc, char*argv[])
{
	if(!rclcpp::ok())
	{
		rclcpp::init(/*argc*/ argc, /*argv*/ argv);
	}

	m_node = rclcpp::Node::make_shared(m_name + "Skill");
	RCLCPP_DEBUG_STREAM(m_node->get_logger(), "StopAndTurnBackSkill::start");
	std::cout << "DEBUG: StopAndTurnBackSkill::start" << std::endl;

  
	m_tickService = m_node->create_service<bt_interfaces_dummy::srv::TickAction>(m_name + "Skill/tick",
                                                                           	std::bind(&StopAndTurnBackSkill::tick,
                                                                           	this,
                                                                           	std::placeholders::_1,
                                                                           	std::placeholders::_2));
  m_tickService->configure_introspection(m_node->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
	m_haltService = m_node->create_service<bt_interfaces_dummy::srv::HaltAction>(m_name + "Skill/halt",
                                                                            	std::bind(&StopAndTurnBackSkill::halt,
                                                                            	this,
                                                                            	std::placeholders::_1,
                                                                            	std::placeholders::_2));
  m_haltService->configure_introspection(m_node->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  
  
  nodeTurnBack = rclcpp::Node::make_shared(m_name + "SkillNodeTurnBack");
  clientTurnBack = nodeTurnBack->create_client<navigation_interfaces::srv::TurnBack>("/NavigationComponent/TurnBack");
  clientTurnBack->configure_introspection(nodeTurnBack->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientTurnBack->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'TurnBack'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'TurnBack'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'NavigationComponent/TurnBack' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("NavigationComponent.TurnBack.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<navigation_interfaces::srv::TurnBack::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientTurnBack->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeTurnBack, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("is_ok", response->is_ok);
           m_stateMachine.submitEvent("NavigationComponent.TurnBack.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.TurnBack.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'TurnBack'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'TurnBack'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("NavigationComponent.TurnBack.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.TurnBack.Return");
  });
  nodeStopNavigation = rclcpp::Node::make_shared(m_name + "SkillNodeStopNavigation");
  clientStopNavigation = nodeStopNavigation->create_client<navigation_interfaces::srv::StopNavigation>("/NavigationComponent/StopNavigation");
  clientStopNavigation->configure_introspection(nodeStopNavigation->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientStopNavigation->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'StopNavigation'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'StopNavigation'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'NavigationComponent/StopNavigation' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("NavigationComponent.StopNavigation.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<navigation_interfaces::srv::StopNavigation::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientStopNavigation->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeStopNavigation, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           m_stateMachine.submitEvent("NavigationComponent.StopNavigation.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.StopNavigation.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'StopNavigation'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'StopNavigation'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("NavigationComponent.StopNavigation.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.StopNavigation.Return");
  });
  nodeGetNavigationStatus = rclcpp::Node::make_shared(m_name + "SkillNodeGetNavigationStatus");
  clientGetNavigationStatus = nodeGetNavigationStatus->create_client<navigation_interfaces::srv::GetNavigationStatus>("/NavigationComponent/GetNavigationStatus");
  clientGetNavigationStatus->configure_introspection(nodeGetNavigationStatus->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientGetNavigationStatus->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'GetNavigationStatus'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'GetNavigationStatus'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'NavigationComponent/GetNavigationStatus' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("NavigationComponent.GetNavigationStatus.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<navigation_interfaces::srv::GetNavigationStatus::Request>();
      auto eventParams = event.data().toMap();
      
      auto result = clientGetNavigationStatus->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeGetNavigationStatus, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("status.status", response->status.status);
           m_stateMachine.submitEvent("NavigationComponent.GetNavigationStatus.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.GetNavigationStatus.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'GetNavigationStatus'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'GetNavigationStatus'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("NavigationComponent.GetNavigationStatus.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "NavigationComponent.GetNavigationStatus.Return");
  });
  nodeSetInt = rclcpp::Node::make_shared(m_name + "SkillNodeSetInt");
  clientSetInt = nodeSetInt->create_client<blackboard_interfaces::srv::SetIntBlackboard>("/BlackboardComponent/SetInt");
  clientSetInt->configure_introspection(nodeSetInt->get_clock(), rclcpp::SystemDefaultsQoS(), RCL_SERVICE_INTROSPECTION_CONTENTS);
  
  {
    bool wait_succeded{true};
    int retries = 0;
    while (!clientSetInt->wait_for_service(std::chrono::seconds(1))) {
        if (!rclcpp::ok()) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Interrupted while waiting for the service 'SetInt'. Exiting.");
            wait_succeded = false;
            break;
        } 
        retries++;
        if(retries == SERVICE_TIMEOUT) {
            RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while waiting for the service 'SetInt'.");
            wait_succeded = false;
            break;
        }
    }
    if (!wait_succeded) {
        RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Service 'BlackboardComponent/SetInt' not available.");
        std::exit(1);
    }
  }
  m_stateMachine.connectToEvent("BlackboardComponent.SetInt.Call", [this]([[maybe_unused]]const QScxmlEvent & event){
      auto request = std::make_shared<blackboard_interfaces::srv::SetIntBlackboard::Request>();
      auto eventParams = event.data().toMap();
      
      request->value = convert<decltype(request->value)>(eventParams["value"].toString().toStdString());
      request->field_name = convert<decltype(request->field_name)>(eventParams["field_name"].toString().toStdString());
      auto result = clientSetInt->async_send_request(request);
      const std::chrono::seconds timeout_duration(SERVICE_TIMEOUT);
      auto futureResult = rclcpp::spin_until_future_complete(nodeSetInt, result, timeout_duration);
      if (futureResult == rclcpp::FutureReturnCode::SUCCESS) 
      {
          auto response = result.get();
           QVariantMap data;
           data.insert("call_succeeded", true);
           data.insert("is_ok", response->is_ok);
           m_stateMachine.submitEvent("BlackboardComponent.SetInt.Return", data);
           RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "BlackboardComponent.SetInt.Return");
           return;
      }
      else if(futureResult == rclcpp::FutureReturnCode::TIMEOUT){
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Timed out while future complete for the service 'SetInt'.");
      }
      else {
          RCLCPP_ERROR(rclcpp::get_logger("rclcpp"), "Failed to call service 'SetInt'.");
      }
      QVariantMap data;
      data.insert("call_succeeded", false);
      m_stateMachine.submitEvent("BlackboardComponent.SetInt.Return", data);
      RCLCPP_INFO(rclcpp::get_logger("rclcpp"), "BlackboardComponent.SetInt.Return");
  });
  
  m_stateMachine.connectToEvent("TICK_RESPONSE", [this]([[maybe_unused]]const QScxmlEvent & event){
    RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::tickReturn %s", event.data().toMap()["status"].toString().toStdString().c_str());
    std::string result = event.data().toMap()["status"].toString().toStdString();
    if (result == std::to_string(SKILL_SUCCESS) )
    {
      m_tickResult.store(Status::success);
    }
    else if (result == std::to_string(SKILL_RUNNING) )
    {
      m_tickResult.store(Status::running);
    }
    else if (result == std::to_string(SKILL_FAILURE) )
    { 
      m_tickResult.store(Status::failure);
    }
  });
    
  m_stateMachine.connectToEvent("HALT_RESPONSE", [this]([[maybe_unused]]const QScxmlEvent & event){
    RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::haltresponse");
    m_haltResult.store(true);
  });

  
  
  
  

	m_stateMachine.start();
	m_threadSpin = std::make_shared<std::thread>(spin, m_node);
       
	return true;
}

void StopAndTurnBackSkill::tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Request> request,
                                std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Response>      response)
{
  std::lock_guard<std::mutex> lock(m_requestMutex);
  RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::tick");
  m_tickResult.store(Status::undefined);
  m_stateMachine.submitEvent("CMD_TICK");
  
  int load_counter=0;
  auto start_timer = std::chrono::steady_clock::now();
  while(m_tickResult.load()== Status::undefined) {
      std::this_thread::sleep_for (std::chrono::milliseconds(5));
      load_counter++;
  }
  auto end_timer = std::chrono::steady_clock::now();
  auto duration_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_timer - start_timer).count();
  switch(m_tickResult.load()) 
  {
      case Status::running:
          response->status = SKILL_RUNNING;
          break;
      case Status::failure:
          response->status = SKILL_FAILURE;
          break;
      case Status::success:
          response->status = SKILL_SUCCESS;
          break;
      case Status::undefined:
          response->status = SKILL_FAILURE;
          break;
  }
  RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::tickDone");
  RCLCPP_DEBUG(m_node->get_logger(), "StopAndTurnBackSkill num_retry: %d tick time: %ld", load_counter, duration_ms);
  response->is_ok = true;
}

void StopAndTurnBackSkill::halt( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Request> request,
    [[maybe_unused]] std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Response> response)
{
  std::lock_guard<std::mutex> lock(m_requestMutex);
  RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::halt");
  m_haltResult.store(false);
  m_stateMachine.submitEvent("CMD_HALT");
  while(!m_haltResult.load()) {
      std::this_thread::sleep_for (std::chrono::milliseconds(100));
  }
  RCLCPP_INFO(m_node->get_logger(), "StopAndTurnBackSkill::haltDone");
  response->is_ok = true;
}








