string[] texts # The text to be spoken
string[] dances # The dance to be performed while speaking
---
bool is_ok
bool is_reply_finished # True if the reply has finished (i.e., all predefined answers have been given)
---
string status