// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-12 11:12:46 UTC
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SayWhileNavigatingSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SayWhileNavigatingSkill stateMachine("SayWhileNavigating");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SayWhileNavigatingSkill successfully closed" << std::endl;
  return ret;
}

