// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-11-26 16:09:55 CET
// This is an automatically generated file.

# pragma once

#include <mutex>
#include <thread>
#include <rclcpp/rclcpp.hpp>
#include "rclcpp_action/rclcpp_action.hpp"
#include "SayByeSkillSM.h"
#include <bt_interfaces_dummy/msg/action_response.hpp>
#include <text_to_speech_interfaces/srv/speak.hpp> 
#include <text_to_speech_interfaces/srv/is_speaking.hpp> 
#include <scheduler_interfaces/srv/set_command.hpp> 
#include <scheduler_interfaces/srv/get_current_action.hpp> 



#include <bt_interfaces_dummy/srv/tick_action.hpp>
#include <bt_interfaces_dummy/srv/halt_action.hpp>

#include <rcl/service_introspection.h>

#define SERVICE_TIMEOUT 8
#define SKILL_SUCCESS 0
#define SKILL_FAILURE 1
#define SKILL_RUNNING 2

enum class Status{
	undefined,
	running, 
	success,
	failure
};

class SayByeSkill
{
public:
	SayByeSkill(std::string name );
    ~SayByeSkill();

	bool start(int argc, char * argv[]);
	static void spin(std::shared_ptr<rclcpp::Node> node);
	
	void tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Request> request,
			   std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Response>      response);
	
	void halt( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Request> request,
			   [[maybe_unused]] std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Response> response);
	
	

private:
	std::shared_ptr<std::thread> m_threadSpin;
	std::shared_ptr<rclcpp::Node> m_node;
	std::mutex m_requestMutex;
	std::string m_name;
	SayByeSkillAction m_stateMachine;
	std::atomic<Status> m_tickResult{Status::undefined};
	rclcpp::Service<bt_interfaces_dummy::srv::TickAction>::SharedPtr m_tickService;
	std::atomic<bool> m_haltResult{false};
	rclcpp::Service<bt_interfaces_dummy::srv::HaltAction>::SharedPtr m_haltService;
	
	
	
	
	std::shared_ptr<rclcpp::Node> nodeSpeak;
	std::shared_ptr<rclcpp::Client<text_to_speech_interfaces::srv::Speak>> clientSpeak;
	std::shared_ptr<rclcpp::Node> nodeIsSpeaking;
	std::shared_ptr<rclcpp::Client<text_to_speech_interfaces::srv::IsSpeaking>> clientIsSpeaking;
	std::shared_ptr<rclcpp::Node> nodeSetCommand;
	std::shared_ptr<rclcpp::Client<scheduler_interfaces::srv::SetCommand>> clientSetCommand;
	std::shared_ptr<rclcpp::Node> nodeGetCurrentAction;
	std::shared_ptr<rclcpp::Client<scheduler_interfaces::srv::GetCurrentAction>> clientGetCurrentAction;
	
	

};

