// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-06-16 17:01:30 CEST with M2C version 1.0.0
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SayByeSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SayByeSkill stateMachine("SayBye");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SayByeSkill successfully closed" << std::endl;
  return ret;
}

