// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-12-01 13:46:37 CET
// This is an automatically generated file.

# pragma once

#include <mutex>
#include <thread>
#include <rclcpp/rclcpp.hpp>
#include "rclcpp_action/rclcpp_action.hpp"
#include "IsAllowedToMoveSkillSM.h"
#include <bt_interfaces_dummy/msg/condition_response.hpp>
#include <allowed_to_move_interfaces/srv/is_allowed_to_move.hpp> 



#include <bt_interfaces_dummy/srv/tick_condition.hpp>


#include <rcl/service_introspection.h>

#define SERVICE_TIMEOUT 8
#define SKILL_SUCCESS 0
#define SKILL_FAILURE 1
#define SKILL_RUNNING 2

enum class Status{
	undefined,
	success,
	failure
};

class IsAllowedToMoveSkill
{
public:
	IsAllowedToMoveSkill(std::string name );
    ~IsAllowedToMoveSkill();

	bool start(int argc, char * argv[]);
	static void spin(std::shared_ptr<rclcpp::Node> node);
	
	void tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Request> request,
			   std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Response>      response);
	
	
	

private:
	std::shared_ptr<std::thread> m_threadSpin;
	std::shared_ptr<rclcpp::Node> m_node;
	std::mutex m_requestMutex;
	std::string m_name;
	IsAllowedToMoveSkillCondition m_stateMachine;
	std::atomic<Status> m_tickResult{Status::undefined};
	rclcpp::Service<bt_interfaces_dummy::srv::TickCondition>::SharedPtr m_tickService;
	
	
	
	
	
	
	std::shared_ptr<rclcpp::Node> nodeIsAllowedToMove;
	std::shared_ptr<rclcpp::Client<allowed_to_move_interfaces::srv::IsAllowedToMove>> clientIsAllowedToMove;
	
	

};

