// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-20 14:28:53 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "SayFollowMeSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  SayFollowMeSkill stateMachine("SayFollowMe");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "SayFollowMeSkill successfully closed" << std::endl;
  return ret;
}

