// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-23 11:47:46 CET
// This is an automatically generated file.

# pragma once

#include <mutex>
#include <thread>
#include <rclcpp/rclcpp.hpp>
#include "rclcpp_action/rclcpp_action.hpp"
#include "StopAndTurnBackSkillSM.h"
#include <bt_interfaces_dummy/msg/action_response.hpp>
#include <navigation_interfaces/srv/turn_back.hpp> 
#include <navigation_interfaces/srv/stop_navigation.hpp> 
#include <navigation_interfaces/srv/get_navigation_status.hpp> 
#include <blackboard_interfaces/srv/set_int_blackboard.hpp> 



#include <bt_interfaces_dummy/srv/tick_action.hpp>
#include <bt_interfaces_dummy/srv/halt_action.hpp>

#include <rcl/service_introspection.h>

#define SERVICE_TIMEOUT 8
#define SKILL_SUCCESS 0
#define SKILL_FAILURE 1
#define SKILL_RUNNING 2

enum class Status{
	undefined,
	running, 
	success,
	failure
};

class StopAndTurnBackSkill
{
public:
	StopAndTurnBackSkill(std::string name );
    ~StopAndTurnBackSkill();

	bool start(int argc, char * argv[]);
	static void spin(std::shared_ptr<rclcpp::Node> node);
	
	void tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Request> request,
			   std::shared_ptr<bt_interfaces_dummy::srv::TickAction::Response>      response);
	
	void halt( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Request> request,
			   [[maybe_unused]] std::shared_ptr<bt_interfaces_dummy::srv::HaltAction::Response> response);
	
	

private:
	std::shared_ptr<std::thread> m_threadSpin;
	std::shared_ptr<rclcpp::Node> m_node;
	std::mutex m_requestMutex;
	std::string m_name;
	StopAndTurnBackSkillAction m_stateMachine;
	std::atomic<Status> m_tickResult{Status::undefined};
	rclcpp::Service<bt_interfaces_dummy::srv::TickAction>::SharedPtr m_tickService;
	std::atomic<bool> m_haltResult{false};
	rclcpp::Service<bt_interfaces_dummy::srv::HaltAction>::SharedPtr m_haltService;
	
	
	
	
	std::shared_ptr<rclcpp::Node> nodeTurnBack;
	std::shared_ptr<rclcpp::Client<navigation_interfaces::srv::TurnBack>> clientTurnBack;
	std::shared_ptr<rclcpp::Node> nodeStopNavigation;
	std::shared_ptr<rclcpp::Client<navigation_interfaces::srv::StopNavigation>> clientStopNavigation;
	std::shared_ptr<rclcpp::Node> nodeGetNavigationStatus;
	std::shared_ptr<rclcpp::Client<navigation_interfaces::srv::GetNavigationStatus>> clientGetNavigationStatus;
	std::shared_ptr<rclcpp::Node> nodeSetInt;
	std::shared_ptr<rclcpp::Client<blackboard_interfaces::srv::SetIntBlackboard>> clientSetInt;
	
	

};

