// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2025-11-26 16:09:55 CET
// This is an automatically generated file.

# pragma once

#include <mutex>
#include <thread>
#include <rclcpp/rclcpp.hpp>
#include "rclcpp_action/rclcpp_action.hpp"
#include "IsAtCurrentPoiSkillSM.h"
#include <bt_interfaces_dummy/msg/condition_response.hpp>
#include <scheduler_interfaces/srv/get_current_poi.hpp> 
#include <navigation_interfaces/srv/get_navigation_status.hpp> 
#include <navigation_interfaces/srv/check_near_to_poi.hpp> 



#include <bt_interfaces_dummy/srv/tick_condition.hpp>


#include <rcl/service_introspection.h>

#define SERVICE_TIMEOUT 8
#define SKILL_SUCCESS 0
#define SKILL_FAILURE 1
#define SKILL_RUNNING 2

enum class Status{
	undefined,
	success,
	failure
};

class IsAtCurrentPoiSkill
{
public:
	IsAtCurrentPoiSkill(std::string name );
    ~IsAtCurrentPoiSkill();

	bool start(int argc, char * argv[]);
	static void spin(std::shared_ptr<rclcpp::Node> node);
	
	void tick( [[maybe_unused]] const std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Request> request,
			   std::shared_ptr<bt_interfaces_dummy::srv::TickCondition::Response>      response);
	
	
	

private:
	std::shared_ptr<std::thread> m_threadSpin;
	std::shared_ptr<rclcpp::Node> m_node;
	std::mutex m_requestMutex;
	std::string m_name;
	IsAtCurrentPoiSkillCondition m_stateMachine;
	std::atomic<Status> m_tickResult{Status::undefined};
	rclcpp::Service<bt_interfaces_dummy::srv::TickCondition>::SharedPtr m_tickService;
	
	
	
	
	
	
	std::shared_ptr<rclcpp::Node> nodeGetCurrentPoi;
	std::shared_ptr<rclcpp::Client<scheduler_interfaces::srv::GetCurrentPoi>> clientGetCurrentPoi;
	std::shared_ptr<rclcpp::Node> nodeGetNavigationStatus;
	std::shared_ptr<rclcpp::Client<navigation_interfaces::srv::GetNavigationStatus>> clientGetNavigationStatus;
	std::shared_ptr<rclcpp::Node> nodeCheckNearToPoi;
	std::shared_ptr<rclcpp::Client<navigation_interfaces::srv::CheckNearToPoi>> clientCheckNearToPoi;
	
	

};

