// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-04-14 16:40:12 CEST with M2C version 1.0.0
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "BatteryChargingSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  BatteryChargingSkill stateMachine("BatteryCharging");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "BatteryChargingSkill successfully closed" << std::endl;
  return ret;
}

