// Autogenerated by model2code (https://github.com/convince-project/model2code)
// File autogenerated at 2026-01-20 15:53:16 CET
// This is an automatically generated file.

#include <QCoreApplication>
#include <QScxmlStateMachine>
#include <QDebug>
#include <iostream>
#include <thread>
#include <chrono>
#include "RunTimerSkill.h"

int main(int argc, char *argv[])
{
  QCoreApplication app(argc, argv);
  RunTimerSkill stateMachine("RunTimer");
  stateMachine.start(argc, argv);

  int ret=app.exec();
  
  std::cout << "RunTimerSkill successfully closed" << std::endl;
  return ret;
}

